# File: .github/workflows/TerraformPlanOnPR.yml

name: 'Terraform Plan on PR'

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan-dev:
    name: Terraform Plan
    runs-on: ubuntu-latest
      
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID_DEV }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }} 
          enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="devbackend.conf"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars


  terraform-plan-prod:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-plan-dev
      
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="prodbackend.conf"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -var-file=prod.tfvars
